### ISSUE TITLE
[use case] Use case / Theme picker design project

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#1462]
https://www.figma.com/design/yeYDP9BJN73U9mMYlhqoJD/HAX-Theme-Picker-Wireframe

Change theme as menu setting on its own.
Add themes common to WordPress / press books
Tag themes using HaxSchema 
Menu button for request theme be added that links into issue queue
Hover animates / plays a gif. This comes from a screenshot of an autogenerated haxcms space using vercel to take the screenshot / scroll. Then 0 maintenance on creation part
Work this as stand alone element so can be added to hax app dashboard as well

- [x] research how GravCMS / Wordpress / W_x and S-uare-pace communicate about themes
- [x] review micro-copy as well as tagging, data, features, filtering and visuals
- [x] Design figma prototype to include this as a stand alone app assuming it reads off a data structure (this should be JOS based structure but it's for theme data instead of page data)
- [x] Review existing themes and update micro-copy
- [x] Generate theme json data by parsing a theme registration json blob (bryan)
- [x] Gap analysis; relative to planned themes in the issue queue, what should we target next?
- [x] Creating the components based on DDD to be the haxcms-theme-picker-item vs theme-picker vs theme-picker-filter controls
- [ ] Visual option for "selected" when it's the currently selected item; event capability for wiring in if picking and setting value `@value-changed` on the `theme-picker` tag
- [ ] Can we remove / reduce the settings that are currently shipped for all themes in this menu (color, icon, logo, banner)
- [ ] envision how this fits into the site settings menu (is it a dialog on it's own and needs a new endpoint or is it just focusing on the settings in metadata being updated but this is not allowing you to modify the rest of it)

**Comment by btopro** [comment]
#1880 possibly related

**Comment by btopro** [comment]
This is Ashley

**Comment by btopro** [comment]
#2492 will finish it off as part of QA
