### ISSUE TITLE
Support dynamic path routing for CMS-like capabilities

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#1640]
This will exist in a hard coded way via #1565 and #1637 but needs to be available in a flexible way so other routes can rapidly be registered by the pieces as they show up. It's almost like there's "page" routing (which we have) and then this is the fallback which is more "app" routing.
- [x] pick a base name like `/x/` or `/_h` that's reserved in the address bar
- [x] x/home
- [x] x/random
- [x] x/views
- [x] x/tags
- [x] x/search
- [ ] add route for login / logout
- [ ] add route for merlin and prepopulating merlin
- [ ] add route for insights
- [ ] add route for outline-designer
- [ ] add route for share site
- [ ] add route for editing site settings
- [ ] route for edit state

**Comment by btopro** [comment]
this should be possible if internalRoutes variable is stateful / maintains changes and additions to itself. If they were all there at the start it would work as currently written
