### ISSUE TITLE
Make Import format tutorial videos

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#1730]
- [x] make an endpoint that assumes HTML much like the MD import stuff
- [x] point to a HTML file  or URL
- [x] make video showing import from DocX
- [x] make video showing import from ELMS:LN
- [x] make video showing import from Notion
- [x] make a video showing import from existing hax space
- [ ] make video showing import from gitbook
- [ ] make video showing import from Drupal 7 (stock + module, make it on reclaim)
- [ ] make video showing import from Drupal 10 (only after fixing import structure)

https://www.youtube.com/watch?v=58AKmH4K-Ec&list=PLlJjKfvF9oaM2N_U31sqp2hMy6lx3g_of

**Comment by btopro** [comment]
source material:
https://online.stat.psu.edu/stat500/book/export/html/547
https://www.e-education.psu.edu/meteo3/print/book/export/html/1940

**Comment by btopro** [comment]
https://oer.hax.psu.edu/bto108/sites/haxcellence/tutorials/migrate-data-to-hax
