### ISSUE TITLE
Create a user scaffold program

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#1790]
this knows the results based on current scaffolding state; start by working with links and short term memory concept
- [x] detect url
- [x] automatically open the merlin results in mini mode
- [x] run the scaffolding program
- [ ] present results
- [ ] click result to modify the operation performed to the active node / thing to do.
