### ISSUE TITLE
add support for URL detection / running the "user scaffold" program if we have no results known

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#1791]
User scaffold program #1790 needs activated if we have no known results; if we have just got a paste of a link for example, then we need to run that program against the input of the field.

- [x] insert URL into page
- [x] insert title of page linking to URL
- [x] if in editMode, just do it when clicking, if not in editMode put in edit mode and add to bottom
- [ ] if we paste in context and match the criteria (replace how that evaluation is currently done) then it hands off to Merlin and focuses the interaction there, but recalls where you just were so that it can insert at the point of the previous operation

This starting point will allow us to start to do additional analysis like it's a youtube or spotify link
