### ISSUE TITLE
[cli] HAX site command

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#2005]
- [x] template a new site just like what we do in HAX11ty (might be able to reuse those files as they are EJS based)
- [x] Need to try and add routes to local server so we can start into the nodeJS API (can start by running individual commands hopefully)
- [ ] ensure there is an area for a base theme to develop if the user desires (theme developer command spins off this) #2004

These will naturally dovetail into the whole command line ops via nodeJS api. Now we've at least got an initial front door.

```
{
  "name": "haxcms-customizations",
  "version": "0.0.0",
  "description": "Custom HAXcms additions, either of a theme or other elements you want to use in this site",
  "author": "HAXTheWeb",
  "homepage": "https://github.com/haxtheweb/haxcms",
  "license": "Apache-2.0",
  "repository": "https://github.com/haxtheweb/haxcms",
  "scripts": {
    "build": "rollup -c rollup.config.js",
    "start": "yarn run watch",
    "watch": "rollup --watch -c rollup.config.js"
  },
  "dependencies": {
  },
  "devDependencies": {
    "rollup-plugin-terser": "5.2.0",
    "rollup-plugin-rewrite-imports": "^1.0.0",
    "rollup": "^1.6.0"
  }
}
```

this is how we used to do it and it gets the job done tho requires tooling to be installed. Would be ideal if there was a way to resolve these in a self contained manner
