### ISSUE TITLE
sub-grouping on input fields

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#2062]
We want to group fonts, spacing, colors, and nest them in collapsed fieldsets. This way it's a lot easier to see everything going on on the side.

`// this will only support a single collapse hiding a whole bunch of values` where I left off

# the issue

simple-fields can't correctly translate that we want the value with empty key pairs. It's not actually nested in the dom, just visually in this one container for organizational purposes.

- [x] review code around "" and collapse in hax-tray
- [x] ensure we can name these and find a viable solution involving something that is a value associated to a collapse. otherwise you can only have 1 collapse
- [x] Not sure it needs to be written recursively, just a single level because we're in a collapse already visually so double nesting would look insane
- [x] this would be the same issue w/ tab and other organizational UI pieces we'd ever come up with so should be holistic
