### ISSUE TITLE
Audit for DDD usage across our portfolio

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#2132]
We started the process and have MOST elements implementing but there are sure to be random `gray` or `--simple-colors-default-theme-accent-1` laying around as opposed to the DDD work that needs to be applied in a uniform manner.
#2115 related for sure and eventually so is #2124
- [x] Review all elements in the monorepo https://github.com/haxtheweb/webcomponents
- [x] Document what is using DDD vs DDDSuper vs SimpleColors vs neither
- [ ] Update all references to (relevant) pixel spacing and color to be moved to DDD and off of prior cruft
- [ ] Implement / update HAX Wiring to implement DDD instead of accentColor methodology from simple colors

# test plan
- Install monorepo
- go to repo under elements/
- start repo, look at the code, quantify if it's using the design system or not and any spacing considerations that are off

**Comment by WilliamMRose** [comment]
Just noting that Peter Rea has a start on this task as I asked him some weeks ago to audit for these. He didn't not finish but made progress. I would have to find the URL where he was documenting.

**Comment by btopro** [comment]
that's 1 aspect and not bad to have but this will be developer layer / more thorough. lacking use of the variables implies it's not actually using the design system. haxProperties using accentColor variable (what you are referencing) is downstream of that but still useful to illustrate the problem. Please add link to this thread as a student will be taking this this semester.

**Comment by btopro** [comment]
Kai is taking this
