### ISSUE TITLE
Update the haxtheweb.org video work 

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#2134]
The "if I want to go to box" video was made in 2018. Wow has HAX come a long way from a moonshot idea to now. 6 years later it's used by people at scale and we don't think about a lot of the UX considerations. Still, the video doing the bulk of communication about the project has visuals from 2018 and looks terrible.

The interviews / voice over work isn't bad but could use a refresh as a separate project. So this is multifacceted

https://www.youtube.com/watch?v=LrS7dqokTLE for reference

- [ ] do screen recordings of the functionality being discussed in the video
- [ ] swap out the visuals currently in this video
- [ ] post this video to hax.psu as part of the marketing of the platform
- [ ] post this to the hax youtube channel as it shouldn't be on my personal channel
- [ ] do postings about this video to get some social push behind it

Then, after that's done, we need to start making small videos of this nature that communicate different concepts in HAX. Possible video topics:

- What is Ubiquity (spoken by me. A cleaned up formalized version of this talk -- https://www.youtube.com/watch?v=Tto2kJPXeH4  (short, 1-2 minutes)
- Why HAX (the case for HAX, probably as spoken by me, Bill, Fusco) (short, 1-2 minutes)
- Why teaching with HAX unlocks creativity (interviews with IDs / faculty) (short, 1-3 minutes)
- How new features are added to HAX (interviews with IDs / faculty) (short, 1-3 minutes)
- Project EdTechJoker - The story behind the creation of HAX Lab and a life long commitment to creating a better web. This is basically the story of me as far as where this process was envisioned, why, and how. Docu-series style, a bit longer but not crazy long (like 7 minutes maybe)
- HAX Lab internship promo. 30 seconds at most. What it is, things we've done, quick interview audio from past students, how to get involved. This is far more marketting focus and flashy.

**Comment by btopro** [comment]
https://github.com/haxtheweb/issues/issues/2134, https://github.com/haxtheweb/issues/issues/2155, https://github.com/haxtheweb/issues/issues/2598
