### ISSUE TITLE
Review color and iconography leveraged in page-break / instructional intention

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#2135]
Long running convo, so when Bill sees this message show up he'll laugh. We need someone to manage the process of identifying icons and colors to be associated with the various terms / concepts that we support in HAX. These tend to be things like "Listen" or "Lab" or "Observe" and while they have colors and iconography, there is no intentionality at present.

- [ ] see what all the terms are, review if they need reduced in set
- [ ] see current icons, come up with possible alternatives for each word as far a concept
- [ ] after getting agreement on the concept, create the icons as 24x24 svgs
- [ ] add them to the full iconset for usage in any project
- [ ] see current colors, verify there's enough difference between colors to start to associate color to icon
- [ ] update the HAXschema related to these so that this is what users can place on the page
- [ ] be happy this is taken care of knowing that there's lots more icon based decisions and UX decisions to audit and come up with better iconography for

**Comment by btopro** [comment]
@nishaneupane - This is part of the list we have. After going to a heading you can set this. We need to audit the colors, icons, and labels for these to ensure the action words all make sense

<img width="243" height="995" alt="Image" src="https://github.com/user-attachments/assets/f36fc2f3-9d8f-495a-aae0-cd268d65c0ca" />

Then in the page it looks like this

<img width="1753" height="490" alt="Image" src="https://github.com/user-attachments/assets/93de8422-e976-44ed-8d1c-cb5b11475690" />

**Comment by chloemartin312** [comment]
https://www.figma.com/design/HDP1CJYIZZQaK59CJLOyqW/ICON-IC-?node-id=0-1&t=3yu45aLCeD2DHGgX-1

<img width="930" height="1240" alt="Image" src="https://github.com/user-attachments/assets/31247c68-7882-4772-bc75-f928a524e0e3" />

**Comment by chloemartin312** [comment]
<img width="941" height="687" alt="Image" src="https://github.com/user-attachments/assets/b916c60f-eb73-4b5e-960e-352b1551ee24" />

**Comment by btopro** [comment]
@WilliamMRose thoughts on the icons proposed. Better than all our chess pieces for everything 😁 🧩

**Comment by btopro** [comment]
@kazmyriad CHLOE SAID YOU ARE GOING TO DRAW THESE THAT SOUNDS AWESOME
