### ISSUE TITLE
Documentation and tutorial audit

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#2136]
We need to start producing more tutorials / how tos / documenting things you can do and how in HAX across the ecosystem. These are things I always want to do but really need people to take, explore and then run with.

- [ ] is our current site (haxcellence) logical in information to new contributors / audiences. Who are we speaking to here
- [ ] After that, What documentation is missing to those different audiences
- [ ] After that, what tutorials are missing to those different audiences
- [ ] A tutorial strategy and style guide. How long are they, scope, what needs covered, what builds on other things
- [ ] Making a tutorial that follows the strategy as a model
- [ ] identifying additional ones and a priority system for future ones

**Comment by btopro** [comment]
added lots of this sorta stuff via IA audit and push out
