### ISSUE TITLE
Support a style-guide.html file in theme

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#2150]
# Rules
- [ ] page-template primary goal is adding templates from the guide to speed up page creation. This means templates show up in that section of block selection and provide a lot of value but are NOT retroactively updated
- [ ] Single item templates that have the `enforce styles` boolean will automatically apply to every tag that matches, but only in areas of style consistency / design system
- [ ] If something already exists, but matches an enforce styles boolean template that only has that tag, then it will apply
- [ ] We need a button to "apply default styles" which resets it to match the demoSchema if the element were to be created just then

# Requirements
- [ ] add a button to a designed area of an existing page for "Send this to the style guide"
- [ ] if something is a template as defined by the user; we need to leave a trace to the id for that template in the HTML. IF this template id is found, it CAN NOT use the styles of the default if told to forcibly apply them. For example a template called "Bill's cool h4" should always look like his h4 even if we've defined a "global" h4 to look a different way.
- [x] need to create an element called `page-template` which just wraps items with a dotted line. This only has settings of Allow overriding colors, and a title to name that template
- [ ] Save with whatever is being put in the page
- [x] Start this file with a page-template wrapping h1, video-player, block-quote, bulleted list
- [x] make a route for `x/theme/style-guide` which has the above loaded
- [x] hax editor is there and can modify this
- [x] add templates to the templates section
- [x] goes to a new route on backend (or leverage save) which saves JUST this file (tho might need setup to support saving similar files as this concept could apply to regions to move them out of the content area)
- [ ] When loading schema for elements in the editor, try loading this file. Convert it to schema and treat each page-template as a template for loading in #2266 
- [x] When loading schema for elements in the editor, if a template exists with only 1 element in it, use this as the hax properties demoSchema (defaulting those original implementations to the demoSchema of the element)
- [ ] If the page-template for a single element (or multiple) allows for setting a color in it's schema, that means the user is able to override this capability
- [ ] Map simpleColors to DDD Colors. Meaning, if we say "orange" have a matching DDD Color `--ddd-orange` woudl be an easy enough way to map this.
- [x] support a setting to override where the styleguide is loaded from. This could lead to issues so would need fallback if load fails and is a more advanced setting for sure
- [ ] On page load, load this if the #2240 says it supports style guides. If it does, load the style guide, convert it to schema, and then if we load any blocks that don't already have a color set, defer to the color set by the style guide
- [ ] Create a selector for simple colors colors which presents them similar to how they are presented in DDD

A similar approach could be used to hide elements you don't want to include in your site.

Having a style guide for the site, as elements on one big page, could solve multiple problems:
- Users want to set "H1 has this blue and this underline" once and not every time they go to it. This would allow us to have defaults relative to a source of truth
- this could be locked by the template so that only certain elements were allowable in that site / theme settings associated
- theme / design implementations could be leveraged to remove items from the common pallet of what's allowed

This would require API expansion so that an element:
- shows up in this display when the site has access to it
- knowing which settings are part of the design defaults so that you aren't setting src and then that's getting updated / synced!

Also need to consider are we updating these values or are they just writing the defaults we provided? Updating retroactively could be problematic as opposed to "oh hey I know the site content says X but you put Y in the theme settings and that means everything this content loads you get Y instead of X". Paired with "But I put X in the content so that takes priority" would allow the best of both. Setting defaults at the theme settings layer that pallet appropriately but allow things that were updated on purpose to remain that way.
