### ISSUE TITLE
Setup HAX on Webcontainer

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#2152]
https://webcontainers.io/ has a library that brings their container building technology to anywhere. We need to publish a new release of nodejs version bc of a single setting to verify this will fix the CORS issues experienced in testing. After that though...

- [x] verify that this will work as a single page and publish a new repo for it
- [x] look into header requirements when in a webcontainer to see if we can get the JS assets to load w/ the correct mimetype
- [x] make an element called `web-container` with options for code to run, if should show terminal, output w/ refresh buttons, etc
- it is not posssible to zip in webcontainers :(
- [x] top level https://hax.cloud/ should be replaced w/ links to demos running locally / demo so that it's just there running w/ site of how to get different versions (desktop, install locations, etc)
- [x] Add links to download the various versions across the top of hax.cloud w/ a brief (i) info box as far as "what is this?"
- [x] write demo on it

This would allow users to build without installing anything if I am to believe what I just made.

# Enhancements

- [x] support files in template tag to load at the start
- [x] support terminal toggle on and off
- [x] editor toggle on and off
- [x] see if we can use code-editor for how we render the editing area
- [x] Find a way that we could automate the setup of projects for testing elements like `<video-player>` #1710 is effectively what this is but this is WAY more advanced than originally scoped.

**Comment by btopro** [comment]
https://hax-webcontainer.vercel.app/
