### ISSUE TITLE
[skeleton api] Create a Skeleton API / scaffold

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#2165]
We need something to capture the settings being discussed in the 'Use case' dashboard that @AshleySantana is working on. Ensuring we have this idea captured as discussed wiith @WilliamMRose in the hall;

- Themes exist
- Settings in those themes exist
- regions exist
- content exists
- currently users have to hit 'i want a course' and then add settings, regions, content manually

The "Use case" dashboard  would ensure everything is a card and that our current themes sorta hide a bit more under a "Start blank" or "Let me do it" kind of option (language still in works). Here's what the API needs to encompass

# API requirements
- [ ] support for name
- [ ] folder / machine name but machine name as prop
- [ ] demo (which invokes hax.cloud demo container system so you can play with it) #2152 
- [ ] screenshot / image
- [ ] optional gif on hover
- [ ] description
- [ ] version number
- [ ] template / theme to select
- [ ] color pallet to preselect. Pallet would be up to 5 
- [ ] regions to automatically associate / populate content with from a `regions/{regionname}.html` structure
- [ ] content to create (may be easier to just include a content folder to load from)
- [ ] files to copy (files folder to associate w/ the content as needed)
- [ ] JOS associating the pages to each other or some nesting

# HAXcms
- [ ] ability to load and store skeletons in the core of the platform.
- [ ] ability to load additional skeletons off the configuration directory

# HAXiam
- [ ] ability to load and store skeletons in the iamConfig directory

## Additional considerations
- we may need to review how we ship / store region data to match above
- we need the core of the platform to identify CSS variables for pallets. This can be upwards of 6 colors and will need to be some kind of css variable like `--hax-pallet-color-1` so that we can set it.
- design systems (like DDD) will then need to supply potential allowable colors for the pallet in question
- elements in the page will then react to the theme/template supplying the mapping between the pallet color and the element. 
- Look to polaris-invent-theme as a vehicle for possible implementation

**Comment by btopro** [comment]
#1462 #2150 as well

**Comment by btopro** [comment]
Closing as there's a ton of work into this and it has many related issues which overlap in the work
